name: Lib Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Lint
        run: npm run test

  may-merge:
    needs: ['tests']
    runs-on: ubuntu-latest
    steps:
      - name: Cleared for merging
        run: echo OK
